name: Deploy on Now
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: deploy
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: --name sandbox --public --no-clipboard deploy .
    - name: release
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: --name sandbox alias --local-config=./now.json
