on: push
name: Deploy on Now
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: --public --no-clipboard deploy . > $HOME/${{ github.action }}.txt
    - name: alias
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: alias `cat $HOME/deploy.txt` ${{ github.sha }}
    - name: master-branch-filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: release
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: alias --local-config=./now.json
