name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
