name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 8
          - 10
          - 12
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm install
  publish:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm view .
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          LATEST=`npm view . version`
          CURRENT=`cat package.json | jq -r .version`
          if [ "$LATEST" != "$CURRENT" ]
          then
            echo ok
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: publish package
        if: github.event_name != 'pull_request'
        run: node -v
